name: Build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Yarn
          run: npm install -g yarn
      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - run: |
          yarn install
          yarn build

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          files: MainModule.rbxmx